Add dockerfile
sandflow/repkl pull request #1
Opened 2023-05-08 02:57 UTC by jaredmcphillen

Created a dockerfile and documentation to use. Ease install, and contain all changes within a separate environment. e.g. python 3.8, pip packages, etc.

2023-06-08 18:19 UTC, palemieux commented
@jaredmcphillen I suggest moving the Dockerfile to a dedicated `container/centos` directory since it is super specific to that OS. Ok?

2023-06-08 18:20 UTC, jaredmcphillen commented
Yes.

2023-06-08 18:30 UTC, palemieux commented
@jaredmcphillen Great. I will merge the PR once you update it.

2023-06-15 02:35 UTC, jaredmcphillen commented
@palemieux made the requested changes.

2023-06-16 00:01 UTC, palemieux requested changes

2023-06-16 00:01 UTC, palemieux commented on README.md
> +## Docker
```suggestion
## CentOS Docker Container 
```

2023-06-18 15:10 UTC, palemieux approved these changes

2023-06-18 15:11 UTC, merged